# Generated by debtap
# Maintainer: ubports-installer_0.11.2
# Contributor: ubports-installer_0.11.2
pkgname=ubports-installer
pkgver=0.11.2
pkgrel=1
pkgdesc="The easy way to install Ubuntu Touch on UBports devices. A friendly cross-platform Installer for Ubuntu Touch. Just connect a supported device to your PC, follow the on-screen instructions and watch this awesome tool do all the rest."
arch=('i686' 'x86_64')
url="https://devices.ubuntu-touch.io"
license=('')
groups=('')
depends_i686=('aarch64-linux-gnu-glibc' 'alsa-lib' 'android-tools' 'at-spi2-core' 'cairo' 'gtk3' 'heimdall' 'gcc-libs' 'glibc' 'libcups' 'libdrm' 'libnotify' 'libx11' 'libxcb' 'libxcomposite' 'libxdamage' 'libxext' 'libxfixes' 'libxkbcommon' 'libxrandr' 'libxtst' 'mesa' 'nspr' 'nss' 'pango')
depends_x86_64=('aarch64-linux-gnu-glibc' 'alsa-lib' 'android-tools' 'at-spi2-core' 'cairo' 'gtk3' 'heimdall' 'lib32-gcc-libs' 'lib32-glibc' 'libcups' 'libdrm' 'libnotify' 'libx11' 'libxcb' 'libxcomposite' 'libxdamage' 'libxext' 'libxfixes' 'libxkbcommon' 'libxrandr' 'libxtst' 'mesa' 'nspr' 'nss' 'pango')
optdepends=('libappindicator')
options=('!strip' '!emptydirs')
install=${pkgname}.install
source_i686=("PUT_FULL_URL_FOR_DOWNLOADING_i386_DEB_PACKAGE_HERE")
source_x86_64=("PUT_FULL_URL_FOR_DOWNLOADING_amd64_DEB_PACKAGE_HERE")
sha512sums_i686=('PUT_SHA512SUM_OF_i386_DEB_PACKAGE_HERE')
sha512sums_x86_64=('9511d40f976a582feb7b3e4f6a520f5b2cf96c209f0bbf36cefe3fe364a6689eab609f26fed895e41109b9a3526fbe24d0c32b6be7b18d6dd906a462ddce797e')

package(){

	# Extract package data
	tar -xJ -f data.tar.xz -C "${pkgdir}"

	install -D -m644 "opt/ubports-installer/resources/app.asar.unpacked/node_modules/universalify/LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

}
