# Generated by debtap
# Maintainer: crossover_26.0.0-1
# Contributor: crossover_26.0.0-1
pkgname=crossover
pkgver=26.0.0
pkgrel=1
pkgdesc="Run Windows productivity and utility apps like Microsoft Office and games. CrossOver integrates with your desktop environment so you can use your Windows applications like any other native application. This includes starting them from the desktop and using them to open Windows files and email attachments. If an anti-virus scanner is available, CrossOver will also automatically scan these to protect you. Thanks to CrossTies, CrossOver takes the guesswork out of installing applications referenced in its compatibility database. This makes it easy to install Windows productivity applications such as Microsoft Office and Quicken. CrossOver also takes care of installing any native packages that may be required to run them. This also applies to games such as Diablo III, Minecraft Dungeons and modern Direct3D 11 and 12 games when it's time to relax."
arch=('i686' 'x86_64')
url="https://www.codeweavers.com"
license=('')
groups=('')
depends_i686=('alsa-lib' 'cuda' 'desktop-file-utils' 'gst-plugins-base-libs' 'gstreamer' 'alsa-lib' 'glib2' 'glibc' 'gnutls' 'libx11' 'libxext' 'systemd' 'wayland' 'libgphoto2' 'libpulse' 'libunwind' 'libx11' 'libxext' 'libxkbcommon' 'ocl-icd' 'pcsclite' 'perl' 'python' 'python-dbus' 'python-gobject' 'sane' 'wayland' 'wine')
depends_x86_64=('alsa-lib' 'cuda' 'desktop-file-utils' 'gst-plugins-base-libs' 'gstreamer' 'lib32-alsa-lib' 'lib32-glib2' 'lib32-glibc' 'lib32-gnutls' 'lib32-libx11' 'lib32-libxext' 'lib32-systemd' 'lib32-wayland' 'libgphoto2' 'libpulse' 'libunwind' 'libx11' 'libxext' 'libxkbcommon' 'ocl-icd' 'pcsclite' 'perl' 'python' 'python-dbus' 'python-gobject' 'sane' 'wayland' 'wine')
options=('!strip' '!emptydirs')
install=${pkgname}.install
source_i686=("PUT_FULL_URL_FOR_DOWNLOADING_i386_DEB_PACKAGE_HERE")
source_x86_64=("PUT_FULL_URL_FOR_DOWNLOADING_amd64_DEB_PACKAGE_HERE")
sha512sums_i686=('PUT_SHA512SUM_OF_i386_DEB_PACKAGE_HERE')
sha512sums_x86_64=('e6a1a69f1b3bbf64bd25d3fda40420d976dce04eec6d1d272abe4d8c62802b908bf1b335f8e8dc8dc7a6c1943da79321e00fbeb9e5a4478367e7b20ec8250eef')

package(){

	# Extract package data
	tar -xJ -f data.tar.xz -C "${pkgdir}"

	install -D -m644 "usr/share/doc/crossover/license.txt.gz" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
	install -D -m644 "usr/share/doc/crossover/copyright" "${pkgdir}/usr/share/licenses/${pkgname}/COPYRIGHT"

}
